modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
[[mods]]
modId="item_color_tutorial"
version="0.0.1"
displayName="Item Color Tutorial"
description='''
Item Color, this Item use Color tag to change color
'''

[[dependencies.item_color_tutorial]]
   modId="forge"
   mandatory=true
   versionRange="[37,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.item_color_tutorial]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.17,1.18)"
   ordering="NONE"
   side="BOTH"
